apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-regions-api
  labels:
    app: treetracker-regions-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treetracker-regions-api
  template:
    metadata:
      labels:
        app: treetracker-regions-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: doks.digitalocean.com/node-pool
                    operator: In
                    values:
                      - default-node-pool
                      - microservices-node-pool
      containers:
        - name: treetracker-regions-api
          image: greenstand/treetracker-regions-api:TAG
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-connection
                  key: db
            - name: DATABASE_SCHEMA
              value: regions
      imagePullSecrets:
        - name: greenstand-docker-secret
